config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'tasks#index'

  get 'tasks' => 'tasks#index'
  get 'tasks/new' => 'tasks#new', as: 'new_task'
  get 'tasks/:id' => 'tasks#show', as: 'task'
  post 'tasks' => 'tasks#create'
  get 'tasks/:id/edit' => 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id' => 'tasks#update'
  delete 'tasks/:id' => 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # validates :user, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:user, :content, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form_for_task.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :user %>
  <%= f.text_field :user %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :done %>
  <%= f.check_box :done, {checked: @task.done} %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-offset-xs-3">

      <%= render 'form_for_task' %>

    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-offset-xs-3">

      <%= link_to "ADD A TASK", "/tasks/new" %>

      <table>
        <thead>
          <th>USER</th>
          <th>CONTENT</th>
          <th>DONE</th>
        </thead>
        <tbody>
          <% @tasks.each_with_index do |task, index| %>
            <tr>
              <td><%= task.user %></td>
              <td><%= task.content %></td>
              <td><%= task.done %></td>
              <td><%= link_to "SEE TASK", task_path(task) %></td>
              <td><%= link_to "DELETE TASK", task_path(task),
                method: :delete,
                data: { confirm: "Are you sure?" } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-offset-xs-3">

      <%= render 'form_for_task' %>

    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-offset-xs-3">
      <h1>USER : <%= @task.user %></h1>
      <br>
      <h1>CONTENT : <%= @task.content %></h1>
      <br>
      <h1>DONE : <%= @task.done %></h1>
      <br>
      <%= link_to "UPDATE THIS TASK", edit_task_path %>
      <br>
      <%= link_to "BACK TO LIST", tasks_path %>
    </div>
  </div>
</div>